name: CD - Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_DEL_SERVIDOR }}
          username: ${{ secrets.USUARIO_SERVIDOR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/lemp-sites/francisco_elisondo/production
            git pull origin main